# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LB.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 900)
        MainWindow.setWindowOpacity(1.0)
        self.LBWindow = QtWidgets.QWidget(MainWindow)
        self.LBWindow.setObjectName("LBWindow")
        self.graphTabBox = QtWidgets.QTabWidget(self.LBWindow)
        self.graphTabBox.setGeometry(QtCore.QRect(330, 29, 1260, 830))
        self.graphTabBox.setAutoFillBackground(False)
        self.graphTabBox.setStyleSheet("")
        self.graphTabBox.setObjectName("graphTabBox")
        self.densityTab = QtWidgets.QWidget()
        self.densityTab.setObjectName("densityTab")
        self.graphTabBox.addTab(self.densityTab, "")
        self.velocityTab = QtWidgets.QWidget()
        self.velocityTab.setObjectName("velocityTab")
        self.graphTabBox.addTab(self.velocityTab, "")
        self.pressureTab = QtWidgets.QWidget()
        self.pressureTab.setObjectName("pressureTab")
        self.graphTabBox.addTab(self.pressureTab, "")
        self.chemicalPotentialTab = QtWidgets.QWidget()
        self.chemicalPotentialTab.setObjectName("chemicalPotentialTab")
        self.graphTabBox.addTab(self.chemicalPotentialTab, "")
        self.simControlBox = QtWidgets.QGroupBox(self.LBWindow)
        self.simControlBox.setGeometry(QtCore.QRect(9, 29, 321, 830))
        self.simControlBox.setTitle("")
        self.simControlBox.setObjectName("simControlBox")
        self.startSimButton = QtWidgets.QPushButton(self.simControlBox)
        self.startSimButton.setGeometry(QtCore.QRect(10, 70, 301, 23))
        self.startSimButton.setObjectName("startSimButton")
        self.stepButton = QtWidgets.QPushButton(self.simControlBox)
        self.stepButton.setGeometry(QtCore.QRect(190, 40, 121, 23))
        self.stepButton.setObjectName("stepButton")
        self.lcdIterations = QtWidgets.QLCDNumber(self.simControlBox)
        self.lcdIterations.setGeometry(QtCore.QRect(70, 10, 241, 25))
        self.lcdIterations.setStyleSheet("QLCDNumber{background-color:rgb(255, 255, 255);}")
        self.lcdIterations.setDigitCount(20)
        self.lcdIterations.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdIterations.setObjectName("lcdIterations")
        self.labelIteration = QtWidgets.QLabel(self.simControlBox)
        self.labelIteration.setGeometry(QtCore.QRect(15, 15, 47, 13))
        self.labelIteration.setObjectName("labelIteration")
        self.initializeButton = QtWidgets.QPushButton(self.simControlBox)
        self.initializeButton.setGeometry(QtCore.QRect(10, 100, 301, 23))
        self.initializeButton.setObjectName("initializeButton")
        self.lineEditStepSize = QtWidgets.QLineEdit(self.simControlBox)
        self.lineEditStepSize.setGeometry(QtCore.QRect(70, 42, 113, 20))
        self.lineEditStepSize.setObjectName("lineEditStepSize")
        self.labelStepSize = QtWidgets.QLabel(self.simControlBox)
        self.labelStepSize.setGeometry(QtCore.QRect(15, 45, 47, 13))
        self.labelStepSize.setObjectName("labelStepSize")
        self.groupBoxInitVariables = QtWidgets.QGroupBox(self.simControlBox)
        self.groupBoxInitVariables.setGeometry(QtCore.QRect(10, 130, 301, 80))
        self.groupBoxInitVariables.setObjectName("groupBoxInitVariables")
        self.labelN1Liquid = QtWidgets.QLabel(self.groupBoxInitVariables)
        self.labelN1Liquid.setGeometry(QtCore.QRect(10, 27, 111, 16))
        self.labelN1Liquid.setObjectName("labelN1Liquid")
        self.labelN1Vapor = QtWidgets.QLabel(self.groupBoxInitVariables)
        self.labelN1Vapor.setGeometry(QtCore.QRect(10, 52, 111, 16))
        self.labelN1Vapor.setObjectName("labelN1Vapor")
        self.lineEditN1Liquid = QtWidgets.QLineEdit(self.groupBoxInitVariables)
        self.lineEditN1Liquid.setGeometry(QtCore.QRect(120, 25, 71, 20))
        self.lineEditN1Liquid.setObjectName("lineEditN1Liquid")
        self.lineEditN1Vapor = QtWidgets.QLineEdit(self.groupBoxInitVariables)
        self.lineEditN1Vapor.setGeometry(QtCore.QRect(120, 50, 71, 20))
        self.lineEditN1Vapor.setObjectName("lineEditN1Vapor")
        self.radioDensityProfileRandom = QtWidgets.QRadioButton(self.groupBoxInitVariables)
        self.radioDensityProfileRandom.setGeometry(QtCore.QRect(228, 29, 61, 17))
        self.radioDensityProfileRandom.setObjectName("radioDensityProfileRandom")
        self.radioDensityProfileStep = QtWidgets.QRadioButton(self.groupBoxInitVariables)
        self.radioDensityProfileStep.setGeometry(QtCore.QRect(228, 51, 61, 17))
        self.radioDensityProfileStep.setObjectName("radioDensityProfileStep")
        self.labelDensityProfileInit = QtWidgets.QLabel(self.groupBoxInitVariables)
        self.labelDensityProfileInit.setGeometry(QtCore.QRect(225, 8, 71, 16))
        self.labelDensityProfileInit.setObjectName("labelDensityProfileInit")
        self.groupBoxDataGeneration = QtWidgets.QGroupBox(self.simControlBox)
        self.groupBoxDataGeneration.setGeometry(QtCore.QRect(10, 216, 301, 181))
        self.groupBoxDataGeneration.setObjectName("groupBoxDataGeneration")
        self.getDensityProfileButton = QtWidgets.QPushButton(self.groupBoxDataGeneration)
        self.getDensityProfileButton.setGeometry(QtCore.QRect(10, 20, 91, 23))
        self.getDensityProfileButton.setObjectName("getDensityProfileButton")
        self.theoryPhaseDiagTempButton = QtWidgets.QPushButton(self.groupBoxDataGeneration)
        self.theoryPhaseDiagTempButton.setGeometry(QtCore.QRect(180, 88, 101, 23))
        self.theoryPhaseDiagTempButton.setObjectName("theoryPhaseDiagTempButton")
        self.theoryPhaseDiagPressButton = QtWidgets.QPushButton(self.groupBoxDataGeneration)
        self.theoryPhaseDiagPressButton.setGeometry(QtCore.QRect(180, 114, 101, 23))
        self.theoryPhaseDiagPressButton.setObjectName("theoryPhaseDiagPressButton")
        self.theoryPhaseDiagChemPotButton = QtWidgets.QPushButton(self.groupBoxDataGeneration)
        self.theoryPhaseDiagChemPotButton.setGeometry(QtCore.QRect(180, 140, 101, 23))
        self.theoryPhaseDiagChemPotButton.setObjectName("theoryPhaseDiagChemPotButton")
        self.labelTheoryPhaseDiagrams = QtWidgets.QLabel(self.groupBoxDataGeneration)
        self.labelTheoryPhaseDiagrams.setGeometry(QtCore.QRect(158, 50, 141, 41))
        self.labelTheoryPhaseDiagrams.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTheoryPhaseDiagrams.setWordWrap(True)
        self.labelTheoryPhaseDiagrams.setObjectName("labelTheoryPhaseDiagrams")
        self.lbPhaseDiagTempButton = QtWidgets.QPushButton(self.groupBoxDataGeneration)
        self.lbPhaseDiagTempButton.setGeometry(QtCore.QRect(20, 88, 101, 23))
        self.lbPhaseDiagTempButton.setObjectName("lbPhaseDiagTempButton")
        self.labelLBPhaseDiagrams = QtWidgets.QLabel(self.groupBoxDataGeneration)
        self.labelLBPhaseDiagrams.setGeometry(QtCore.QRect(25, 50, 91, 41))
        self.labelLBPhaseDiagrams.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLBPhaseDiagrams.setWordWrap(True)
        self.labelLBPhaseDiagrams.setObjectName("labelLBPhaseDiagrams")
        self.lbPhaseDiagPressButton = QtWidgets.QPushButton(self.groupBoxDataGeneration)
        self.lbPhaseDiagPressButton.setGeometry(QtCore.QRect(20, 114, 101, 23))
        self.lbPhaseDiagPressButton.setObjectName("lbPhaseDiagPressButton")
        self.lbPhaseDiagChemPotButton = QtWidgets.QPushButton(self.groupBoxDataGeneration)
        self.lbPhaseDiagChemPotButton.setGeometry(QtCore.QRect(20, 140, 101, 23))
        self.lbPhaseDiagChemPotButton.setObjectName("lbPhaseDiagChemPotButton")
        self.groupBoxConstraints = QtWidgets.QGroupBox(self.simControlBox)
        self.groupBoxConstraints.setGeometry(QtCore.QRect(10, 405, 301, 261))
        self.groupBoxConstraints.setObjectName("groupBoxConstraints")
        self.layoutWidget = QtWidgets.QWidget(self.groupBoxConstraints)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 18, 281, 233))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayoutConstraints = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayoutConstraints.setContentsMargins(0, 0, 0, 0)
        self.gridLayoutConstraints.setObjectName("gridLayoutConstraints")
        self.labelOmega = QtWidgets.QLabel(self.layoutWidget)
        self.labelOmega.setObjectName("labelOmega")
        self.gridLayoutConstraints.addWidget(self.labelOmega, 0, 0, 1, 1)
        self.lineEditOmega = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditOmega.setObjectName("lineEditOmega")
        self.gridLayoutConstraints.addWidget(self.lineEditOmega, 0, 1, 1, 2)
        self.labelAmp = QtWidgets.QLabel(self.layoutWidget)
        self.labelAmp.setObjectName("labelAmp")
        self.gridLayoutConstraints.addWidget(self.labelAmp, 0, 4, 1, 1)
        self.lineEditAmp = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditAmp.setObjectName("lineEditAmp")
        self.gridLayoutConstraints.addWidget(self.lineEditAmp, 0, 5, 1, 1)
        self.labelTc = QtWidgets.QLabel(self.layoutWidget)
        self.labelTc.setObjectName("labelTc")
        self.gridLayoutConstraints.addWidget(self.labelTc, 1, 0, 1, 1)
        self.lineEditTc = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditTc.setObjectName("lineEditTc")
        self.gridLayoutConstraints.addWidget(self.lineEditTc, 1, 1, 1, 2)
        self.labelN0 = QtWidgets.QLabel(self.layoutWidget)
        self.labelN0.setObjectName("labelN0")
        self.gridLayoutConstraints.addWidget(self.labelN0, 1, 4, 1, 1)
        self.lineEditN0 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditN0.setObjectName("lineEditN0")
        self.gridLayoutConstraints.addWidget(self.lineEditN0, 1, 5, 1, 1)
        self.labelNc = QtWidgets.QLabel(self.layoutWidget)
        self.labelNc.setObjectName("labelNc")
        self.gridLayoutConstraints.addWidget(self.labelNc, 2, 0, 1, 1)
        self.lineEditNc = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditNc.setText("")
        self.lineEditNc.setObjectName("lineEditNc")
        self.gridLayoutConstraints.addWidget(self.lineEditNc, 2, 1, 1, 2)
        self.labelT0 = QtWidgets.QLabel(self.layoutWidget)
        self.labelT0.setObjectName("labelT0")
        self.gridLayoutConstraints.addWidget(self.labelT0, 2, 4, 1, 1)
        self.lineEditT0 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditT0.setObjectName("lineEditT0")
        self.gridLayoutConstraints.addWidget(self.lineEditT0, 2, 5, 1, 1)
        self.labelPc = QtWidgets.QLabel(self.layoutWidget)
        self.labelPc.setObjectName("labelPc")
        self.gridLayoutConstraints.addWidget(self.labelPc, 3, 0, 1, 1)
        self.lineEditPc = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditPc.setText("")
        self.lineEditPc.setObjectName("lineEditPc")
        self.gridLayoutConstraints.addWidget(self.lineEditPc, 3, 1, 1, 2)
        self.labelTheta = QtWidgets.QLabel(self.layoutWidget)
        self.labelTheta.setObjectName("labelTheta")
        self.gridLayoutConstraints.addWidget(self.labelTheta, 3, 4, 1, 1)
        self.lineEditTheta = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditTheta.setObjectName("lineEditTheta")
        self.gridLayoutConstraints.addWidget(self.lineEditTheta, 3, 5, 1, 1)
        self.labelG = QtWidgets.QLabel(self.layoutWidget)
        self.labelG.setObjectName("labelG")
        self.gridLayoutConstraints.addWidget(self.labelG, 4, 0, 1, 1)
        self.lineEditG = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditG.setText("")
        self.lineEditG.setObjectName("lineEditG")
        self.gridLayoutConstraints.addWidget(self.lineEditG, 4, 1, 1, 2)
        self.lineEditLambda = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditLambda.setObjectName("lineEditLambda")
        self.gridLayoutConstraints.addWidget(self.lineEditLambda, 4, 5, 1, 1)
        self.labelA1 = QtWidgets.QLabel(self.layoutWidget)
        self.labelA1.setObjectName("labelA1")
        self.gridLayoutConstraints.addWidget(self.labelA1, 5, 0, 1, 1)
        self.lineEditA1 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditA1.setText("")
        self.lineEditA1.setObjectName("lineEditA1")
        self.gridLayoutConstraints.addWidget(self.lineEditA1, 5, 1, 1, 2)
        self.lineEditB1 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditB1.setObjectName("lineEditB1")
        self.gridLayoutConstraints.addWidget(self.lineEditB1, 5, 5, 1, 1)
        self.labelPressMethodCorrection = QtWidgets.QLabel(self.layoutWidget)
        self.labelPressMethodCorrection.setObjectName("labelPressMethodCorrection")
        self.gridLayoutConstraints.addWidget(self.labelPressMethodCorrection, 6, 0, 1, 4)
        self.lineEditPressMethodCorrection = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditPressMethodCorrection.setText("")
        self.lineEditPressMethodCorrection.setObjectName("lineEditPressMethodCorrection")
        self.gridLayoutConstraints.addWidget(self.lineEditPressMethodCorrection, 6, 4, 1, 2)
        self.labelGammaP = QtWidgets.QLabel(self.layoutWidget)
        self.labelGammaP.setObjectName("labelGammaP")
        self.gridLayoutConstraints.addWidget(self.labelGammaP, 7, 0, 1, 2)
        self.lineEditGammaP = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditGammaP.setText("")
        self.lineEditGammaP.setObjectName("lineEditGammaP")
        self.gridLayoutConstraints.addWidget(self.lineEditGammaP, 7, 2, 1, 1)
        self.labelGammaMu = QtWidgets.QLabel(self.layoutWidget)
        self.labelGammaMu.setObjectName("labelGammaMu")
        self.gridLayoutConstraints.addWidget(self.labelGammaMu, 7, 3, 1, 2)
        self.lineEditGammaMu = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditGammaMu.setObjectName("lineEditGammaMu")
        self.gridLayoutConstraints.addWidget(self.lineEditGammaMu, 7, 5, 1, 1)
        self.labelKappa = QtWidgets.QLabel(self.layoutWidget)
        self.labelKappa.setObjectName("labelKappa")
        self.gridLayoutConstraints.addWidget(self.labelKappa, 8, 0, 1, 2)
        self.lineEditKappa = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditKappa.setText("")
        self.lineEditKappa.setObjectName("lineEditKappa")
        self.gridLayoutConstraints.addWidget(self.lineEditKappa, 8, 2, 1, 1)
        self.autoKappaGammaMuButton = QtWidgets.QPushButton(self.layoutWidget)
        self.autoKappaGammaMuButton.setObjectName("autoKappaGammaMuButton")
        self.gridLayoutConstraints.addWidget(self.autoKappaGammaMuButton, 8, 3, 1, 3)
        self.labelLambda = QtWidgets.QLabel(self.layoutWidget)
        self.labelLambda.setObjectName("labelLambda")
        self.gridLayoutConstraints.addWidget(self.labelLambda, 4, 4, 1, 1)
        self.labelB1 = QtWidgets.QLabel(self.layoutWidget)
        self.labelB1.setObjectName("labelB1")
        self.gridLayoutConstraints.addWidget(self.labelB1, 5, 4, 1, 1)
        self.groupBoxAlgorithms = QtWidgets.QGroupBox(self.simControlBox)
        self.groupBoxAlgorithms.setGeometry(QtCore.QRect(10, 673, 301, 151))
        self.groupBoxAlgorithms.setObjectName("groupBoxAlgorithms")
        self.radioForceNewGradP = QtWidgets.QRadioButton(self.groupBoxAlgorithms)
        self.radioForceNewGradP.setGeometry(QtCore.QRect(10, 20, 111, 17))
        self.radioForceNewGradP.setObjectName("radioForceNewGradP")
        self.radioForceNewGradMu = QtWidgets.QRadioButton(self.groupBoxAlgorithms)
        self.radioForceNewGradMu.setGeometry(QtCore.QRect(10, 42, 121, 17))
        self.radioForceNewGradMu.setObjectName("radioForceNewGradMu")
        self.radioForceBasic = QtWidgets.QRadioButton(self.groupBoxAlgorithms)
        self.radioForceBasic.setGeometry(QtCore.QRect(10, 87, 81, 17))
        self.radioForceBasic.setObjectName("radioForceBasic")
        self.radioPressureMethod = QtWidgets.QRadioButton(self.groupBoxAlgorithms)
        self.radioPressureMethod.setGeometry(QtCore.QRect(10, 65, 101, 17))
        self.radioPressureMethod.setObjectName("radioPressureMethod")
        self.radioForceAlexander = QtWidgets.QRadioButton(self.groupBoxAlgorithms)
        self.radioForceAlexander.setGeometry(QtCore.QRect(10, 108, 111, 17))
        self.radioForceAlexander.setObjectName("radioForceAlexander")
        self.radioForceKyoto = QtWidgets.QRadioButton(self.groupBoxAlgorithms)
        self.radioForceKyoto.setGeometry(QtCore.QRect(10, 130, 91, 17))
        self.radioForceKyoto.setObjectName("radioForceKyoto")
        self.labelHoldychCorrection = QtWidgets.QLabel(self.groupBoxAlgorithms)
        self.labelHoldychCorrection.setGeometry(QtCore.QRect(170, 130, 51, 16))
        self.labelHoldychCorrection.setObjectName("labelHoldychCorrection")
        self.lineEditHoldychCorrection = QtWidgets.QLineEdit(self.groupBoxAlgorithms)
        self.lineEditHoldychCorrection.setGeometry(QtCore.QRect(220, 128, 71, 20))
        self.lineEditHoldychCorrection.setText("")
        self.lineEditHoldychCorrection.setObjectName("lineEditHoldychCorrection")
        self.labelLaplaceCorrection = QtWidgets.QLabel(self.groupBoxAlgorithms)
        self.labelLaplaceCorrection.setGeometry(QtCore.QRect(170, 107, 51, 16))
        self.labelLaplaceCorrection.setObjectName("labelLaplaceCorrection")
        self.lineEditLaplaceCorrection = QtWidgets.QLineEdit(self.groupBoxAlgorithms)
        self.lineEditLaplaceCorrection.setGeometry(QtCore.QRect(220, 105, 71, 20))
        self.lineEditLaplaceCorrection.setText("")
        self.lineEditLaplaceCorrection.setObjectName("lineEditLaplaceCorrection")
        self.labelPressMethodCorrections = QtWidgets.QLabel(self.groupBoxAlgorithms)
        self.labelPressMethodCorrections.setGeometry(QtCore.QRect(162, 85, 131, 20))
        self.labelPressMethodCorrections.setObjectName("labelPressMethodCorrections")
        self.checkBoxPressCoupled = QtWidgets.QCheckBox(self.groupBoxAlgorithms)
        self.checkBoxPressCoupled.setGeometry(QtCore.QRect(170, 10, 111, 17))
        self.checkBoxPressCoupled.setObjectName("checkBoxPressCoupled")
        self.checkBoxChemPotCoupled = QtWidgets.QCheckBox(self.groupBoxAlgorithms)
        self.checkBoxChemPotCoupled.setGeometry(QtCore.QRect(170, 50, 121, 17))
        self.checkBoxChemPotCoupled.setObjectName("checkBoxChemPotCoupled")
        self.checkBoxPressCriticalConst = QtWidgets.QCheckBox(self.groupBoxAlgorithms)
        self.checkBoxPressCriticalConst.setGeometry(QtCore.QRect(188, 28, 111, 17))
        self.checkBoxPressCriticalConst.setObjectName("checkBoxPressCriticalConst")
        self.checkBoxChemPotNid = QtWidgets.QCheckBox(self.groupBoxAlgorithms)
        self.checkBoxChemPotNid.setGeometry(QtCore.QRect(188, 68, 111, 17))
        self.checkBoxChemPotNid.setObjectName("checkBoxChemPotNid")
        self.splitterGraphConfig = QtWidgets.QSplitter(self.LBWindow)
        self.splitterGraphConfig.setGeometry(QtCore.QRect(1110, 15, 475, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitterGraphConfig.sizePolicy().hasHeightForWidth())
        self.splitterGraphConfig.setSizePolicy(sizePolicy)
        self.splitterGraphConfig.setOrientation(QtCore.Qt.Horizontal)
        self.splitterGraphConfig.setObjectName("splitterGraphConfig")
        self.plotComponentBox = QtWidgets.QComboBox(self.splitterGraphConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotComponentBox.sizePolicy().hasHeightForWidth())
        self.plotComponentBox.setSizePolicy(sizePolicy)
        self.plotComponentBox.setObjectName("plotComponentBox")
        self.plotComponentBox.addItem("")
        self.plotLineTypeBox = QtWidgets.QComboBox(self.splitterGraphConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotLineTypeBox.sizePolicy().hasHeightForWidth())
        self.plotLineTypeBox.setSizePolicy(sizePolicy)
        self.plotLineTypeBox.setObjectName("plotLineTypeBox")
        self.plotLineTypeBox.addItem("")
        self.plotLineTypeBox.addItem("")
        self.plotLineTypeBox.addItem("")
        self.plotLineTypeBox.addItem("")
        self.plotLineColorBox = QtWidgets.QComboBox(self.splitterGraphConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotLineColorBox.sizePolicy().hasHeightForWidth())
        self.plotLineColorBox.setSizePolicy(sizePolicy)
        self.plotLineColorBox.setObjectName("plotLineColorBox")
        self.plotLineColorBox.addItem("")
        self.plotLineColorBox.addItem("")
        self.plotLineColorBox.addItem("")
        self.plotLineColorBox.addItem("")
        self.plotLineColorBox.addItem("")
        self.plotLineColorBox.addItem("")
        self.plotLineColorBox.addItem("")
        self.plotLineThicknessBox = QtWidgets.QComboBox(self.splitterGraphConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotLineThicknessBox.sizePolicy().hasHeightForWidth())
        self.plotLineThicknessBox.setSizePolicy(sizePolicy)
        self.plotLineThicknessBox.setObjectName("plotLineThicknessBox")
        self.plotLineThicknessBox.addItem("")
        self.plotLineThicknessBox.addItem("")
        self.plotLineThicknessBox.addItem("")
        self.plotLineSymbols = QtWidgets.QComboBox(self.splitterGraphConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotLineSymbols.sizePolicy().hasHeightForWidth())
        self.plotLineSymbols.setSizePolicy(sizePolicy)
        self.plotLineSymbols.setObjectName("plotLineSymbols")
        self.plotLineSymbols.addItem("")
        self.plotLineSymbols.addItem("")
        self.plotLineSymbols.addItem("")
        self.plotLineSymbols.addItem("")
        self.plotLineSymbols.addItem("")
        MainWindow.setCentralWidget(self.LBWindow)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1600, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.graphTabBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Lattice Boltzmann Simulation"))
        self.graphTabBox.setTabText(self.graphTabBox.indexOf(self.densityTab), _translate("MainWindow", "Density"))
        self.graphTabBox.setTabText(self.graphTabBox.indexOf(self.velocityTab), _translate("MainWindow", "Velocity"))
        self.graphTabBox.setTabText(self.graphTabBox.indexOf(self.pressureTab), _translate("MainWindow", "Pressure"))
        self.graphTabBox.setTabText(self.graphTabBox.indexOf(self.chemicalPotentialTab), _translate("MainWindow", "Chemical Potential"))
        self.startSimButton.setText(_translate("MainWindow", "Start Simulation"))
        self.stepButton.setText(_translate("MainWindow", "Step"))
        self.labelIteration.setText(_translate("MainWindow", "Iteration"))
        self.initializeButton.setText(_translate("MainWindow", "Initialize"))
        self.labelStepSize.setText(_translate("MainWindow", "Step Size"))
        self.groupBoxInitVariables.setTitle(_translate("MainWindow", "Initialization Variables"))
        self.labelN1Liquid.setText(_translate("MainWindow", "Component 1 - Liquid"))
        self.labelN1Vapor.setText(_translate("MainWindow", "Component 1 - Vapor"))
        self.radioDensityProfileRandom.setText(_translate("MainWindow", "Random"))
        self.radioDensityProfileStep.setText(_translate("MainWindow", "Step"))
        self.labelDensityProfileInit.setText(_translate("MainWindow", "Density Profile"))
        self.groupBoxDataGeneration.setTitle(_translate("MainWindow", "Data Generation"))
        self.getDensityProfileButton.setText(_translate("MainWindow", "Density Profile"))
        self.theoryPhaseDiagTempButton.setText(_translate("MainWindow", "Temperature"))
        self.theoryPhaseDiagPressButton.setText(_translate("MainWindow", "Pressure"))
        self.theoryPhaseDiagChemPotButton.setText(_translate("MainWindow", "Chemical Potential"))
        self.labelTheoryPhaseDiagrams.setText(_translate("MainWindow", "Theoretical Phase Diagrams Density vs."))
        self.lbPhaseDiagTempButton.setText(_translate("MainWindow", "Temperature"))
        self.labelLBPhaseDiagrams.setText(_translate("MainWindow", "LB Phase Diagrams Density vs."))
        self.lbPhaseDiagPressButton.setText(_translate("MainWindow", "Pressure"))
        self.lbPhaseDiagChemPotButton.setText(_translate("MainWindow", "Chemical Potential"))
        self.groupBoxConstraints.setTitle(_translate("MainWindow", "Constraints"))
        self.labelOmega.setText(_translate("MainWindow", "omega"))
        self.labelAmp.setText(_translate("MainWindow", "Amp"))
        self.labelTc.setText(_translate("MainWindow", "tc"))
        self.labelN0.setText(_translate("MainWindow", "n0"))
        self.labelNc.setText(_translate("MainWindow", "nc"))
        self.labelT0.setText(_translate("MainWindow", "T0"))
        self.labelPc.setText(_translate("MainWindow", "pc"))
        self.labelTheta.setText(_translate("MainWindow", "theta"))
        self.labelG.setText(_translate("MainWindow", "g"))
        self.labelA1.setText(_translate("MainWindow", "a1"))
        self.labelPressMethodCorrection.setText(_translate("MainWindow", "pressureMethodCorrection"))
        self.labelGammaP.setText(_translate("MainWindow", "gamma-P"))
        self.labelGammaMu.setText(_translate("MainWindow", "gamma-mu"))
        self.labelKappa.setText(_translate("MainWindow", "kappa"))
        self.autoKappaGammaMuButton.setText(_translate("MainWindow", "Auto kappa, gamma-mu"))
        self.labelLambda.setText(_translate("MainWindow", "lambda"))
        self.labelB1.setText(_translate("MainWindow", "b1"))
        self.groupBoxAlgorithms.setTitle(_translate("MainWindow", "Algorithms"))
        self.radioForceNewGradP.setText(_translate("MainWindow", "Force new (grad-P)"))
        self.radioForceNewGradMu.setText(_translate("MainWindow", "Force new (grad-mu)"))
        self.radioForceBasic.setText(_translate("MainWindow", "Force - basic"))
        self.radioPressureMethod.setText(_translate("MainWindow", "Pressure method"))
        self.radioForceAlexander.setText(_translate("MainWindow", "Force - Alexander"))
        self.radioForceKyoto.setText(_translate("MainWindow", "Force - Kyoto"))
        self.labelHoldychCorrection.setText(_translate("MainWindow", "Holdych"))
        self.labelLaplaceCorrection.setText(_translate("MainWindow", "Laplace"))
        self.labelPressMethodCorrections.setText(_translate("MainWindow", "Press. Method Corrections"))
        self.checkBoxPressCoupled.setText(_translate("MainWindow", "Pressure - coupled"))
        self.checkBoxChemPotCoupled.setText(_translate("MainWindow", "Chem. Pot. - coupled"))
        self.checkBoxPressCriticalConst.setText(_translate("MainWindow", "Critical Constants"))
        self.checkBoxChemPotNid.setText(_translate("MainWindow", "Non-ideal"))
        self.plotComponentBox.setItemText(0, _translate("MainWindow", "Component 1"))
        self.plotLineTypeBox.setItemText(0, _translate("MainWindow", "Solid Line"))
        self.plotLineTypeBox.setItemText(1, _translate("MainWindow", "Dashed Line"))
        self.plotLineTypeBox.setItemText(2, _translate("MainWindow", "Dotted Line"))
        self.plotLineTypeBox.setItemText(3, _translate("MainWindow", "Dash-Dot Line"))
        self.plotLineColorBox.setItemText(0, _translate("MainWindow", "Black Line"))
        self.plotLineColorBox.setItemText(1, _translate("MainWindow", "Red Line"))
        self.plotLineColorBox.setItemText(2, _translate("MainWindow", "Blue Line"))
        self.plotLineColorBox.setItemText(3, _translate("MainWindow", "Green Line"))
        self.plotLineColorBox.setItemText(4, _translate("MainWindow", "Yellow Line"))
        self.plotLineColorBox.setItemText(5, _translate("MainWindow", "Orange Line"))
        self.plotLineColorBox.setItemText(6, _translate("MainWindow", "Purple Line"))
        self.plotLineThicknessBox.setItemText(0, _translate("MainWindow", "Thickness 1"))
        self.plotLineThicknessBox.setItemText(1, _translate("MainWindow", "Thickness 2"))
        self.plotLineThicknessBox.setItemText(2, _translate("MainWindow", "Thickness 3"))
        self.plotLineSymbols.setItemText(0, _translate("MainWindow", "No Symbols"))
        self.plotLineSymbols.setItemText(1, _translate("MainWindow", "Circles"))
        self.plotLineSymbols.setItemText(2, _translate("MainWindow", "Squares"))
        self.plotLineSymbols.setItemText(3, _translate("MainWindow", "Triangles"))
        self.plotLineSymbols.setItemText(4, _translate("MainWindow", "Diamonds"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

